language: ruby
rvm:
- 2.3.3

install: gem install jekyll html-proofer jekyll-sitemap jekyll-feed
script: jekyll build --drafts --future --unpublished --verbose --strict_front_matter && htmlproofer ./_site --disable-external

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
