language: ruby
rvm:
- head

install: gem install jekyll html-proofer jekyll-sitemap jekyll-feed
script: jekyll build --drafts --future --unpublished --verbose && htmlproofer ./_site --disable-external

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
